version: "3"
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    network_mode: bridge
    links:
      - socket-server
    volumes:
      - ./public:/app
      - ./docker/web/site.conf:/etc/nginx/conf.d/default.conf
  socket-server:
    build: docker/socket-server/
    ports:
      - "3000:3000"
    network_mode: bridge
    volumes:
      - ./:/app