// flow-typed signature: 518ccb1a9e976485aca29832386c4b58
// flow-typed version: <<STUB>>/iplocation_v^5.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'iplocation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'iplocation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'iplocation/index' {
  declare module.exports: $Exports<'iplocation'>;
}
declare module 'iplocation/index.js' {
  declare module.exports: $Exports<'iplocation'>;
}
