// flow-typed signature: 72345b59b3bec05a61aca8dc35584bf0
// flow-typed version: <<STUB>>/typography-theme-twin-peaks_v^0.15.11/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typography-theme-twin-peaks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typography-theme-twin-peaks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'typography-theme-twin-peaks/dist/index' {
  declare module.exports: any;
}

declare module 'typography-theme-twin-peaks/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'typography-theme-twin-peaks/dist/index.js' {
  declare module.exports: $Exports<'typography-theme-twin-peaks/dist/index'>;
}
declare module 'typography-theme-twin-peaks/src/index.js' {
  declare module.exports: $Exports<'typography-theme-twin-peaks/src/index'>;
}
